---
name: "Sanity Check"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v2
      -
        name: "Setup Environment"
        run: |
          git clone https://github.com/Scene-Collective/ps4-payload-sdk ~/ps4-payload-sdk && cd "$_"
          chmod +x install.sh
          ./install.sh
      -
        name: "Build Payload"
        run: |
          export PS4SDK="$(echo $HOME)/PS4SDK"
          make
      -
        name: "Upload Binary Artifact"
        uses: actions/upload-artifact@v2
        with:
          path: ./*.bin
          if-no-files-found: error
      -
        name: "Upload Map Artifact"
        uses: actions/upload-artifact@v2
        with:
          path: ./*.map
          if-no-files-found: error
